import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { format } from "date-fns";
import { supabase } from "@/integrations/supabase/client";
import { ProofCard } from "@/components/receipt/templates/ProofCardTemplate";
import { Loader2 } from "lucide-react";

export const Route = createFileRoute("/share/proof/$receiptId")({
  component: SharedProofPage,
  head: () => ({
    meta: [
      { title: "Proof of judgment — Charlotte Labs" },
      {
        name: "description",
        content: "A verified snapshot of judgment, verification, and risk flagging from one AI session.",
      },
      { property: "og:title", content: "Proof of judgment — Charlotte Labs" },
      {
        property: "og:description",
        content: "Turn one session into shareable proof of judgment.",
      },
    ],
  }),
  errorComponent: ({ error }) => (
    <div className="min-h-screen flex items-center justify-center p-6 text-sm text-muted-foreground">
      {error.message}
    </div>
  ),
  notFoundComponent: () => (
    <div className="min-h-screen flex items-center justify-center p-6 text-sm text-muted-foreground">
      This proof card is not available.
    </div>
  ),
});

interface RenderingPayload {
  judgment_count?: number;
  verification_count?: number;
  risks_count?: number;
  tool_stack?: string[];
  lead_quote?: { content: string | null; turnIdx: number; unavailable: boolean } | null;
  session_at?: string | null;
}

function SharedProofPage() {
  const { receiptId } = Route.useParams();
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [payload, setPayload] = useState<RenderingPayload | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const { data, error } = await supabase
          .from("renderings")
          .select("payload")
          .eq("receipt_id", receiptId)
          .eq("template_key", "proof_card")
          .maybeSingle();
        if (cancelled) return;
        if (error || !data) {
          setNotFound(true);
        } else {
          setPayload((data as any).payload as RenderingPayload);
        }
      } catch (e) {
        console.error("shared proof load failed", e);
        if (!cancelled) setNotFound(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [receiptId]);

  return (
    <div
      className="min-h-screen w-full py-12 px-4"
      style={{ backgroundColor: "#F4F2ED" }}
    >
      <div className="max-w-lg mx-auto">
        {loading ? (
          <div className="flex items-center gap-2 text-sm text-muted-foreground p-8">
            <Loader2 className="h-4 w-4 animate-spin" />
            Loading proof card…
          </div>
        ) : notFound || !payload ? (
          <div className="rounded-lg border bg-card p-6 text-sm text-muted-foreground">
            This proof card is not available. The owner may have made it private.
          </div>
        ) : (
          <>
            <ProofCard
              judgmentCount={payload.judgment_count ?? 0}
              verificationCount={payload.verification_count ?? 0}
              risksCount={payload.risks_count ?? 0}
              toolStack={payload.tool_stack ?? []}
              leadQuote={payload.lead_quote ?? null}
              sessionDate={
                payload.session_at
                  ? format(new Date(payload.session_at), "MMM d, yyyy")
                  : null
              }
            />
            <p className="text-xs text-muted-foreground text-center mt-4">
              Generated by Charlotte Labs. Counts inferred from behavioral signals.
            </p>
          </>
        )}
      </div>
    </div>
  );
}
