/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticipantIndexRouteImport } from './routes/participant.index'
import { Route as ParticipantWorkspacesRouteImport } from './routes/participant.workspaces'
import { Route as ParticipantFingerprintRouteImport } from './routes/participant.fingerprint'
import { Route as ParticipantExtensionRouteImport } from './routes/participant.extension'
import { Route as ParticipantDepartmentRouteImport } from './routes/participant.department'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ParticipantThreadsIndexRouteImport } from './routes/participant.threads.index'
import { Route as ParticipantReceiptsIndexRouteImport } from './routes/participant.receipts.index'
import { Route as ParticipantWorkspacesWorkspaceIdRouteImport } from './routes/participant.workspaces.$workspaceId'
import { Route as ParticipantThreadsNewRouteImport } from './routes/participant.threads.new'
import { Route as ParticipantThreadsThreadIdRouteImport } from './routes/participant.threads.$threadId'
import { Route as ParticipantReceiptsReceiptIdRouteImport } from './routes/participant.receipts.$receiptId'
import { Route as ParticipantDepartmentClassIdRouteImport } from './routes/participant.department.$classId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTeamOutreachRouteImport } from './routes/api/public/team-outreach'
import { Route as ApiPublicExtensionStatusRouteImport } from './routes/api/public/extension-status'
import { Route as ApiPublicCaptureConversationRouteImport } from './routes/api/public/capture-conversation'
import { Route as ParticipantDepartmentClassIdThreadsRouteImport } from './routes/participant.department.$classId.threads'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksProcessThreadJobsRouteImport } from './routes/api/public/hooks/process-thread-jobs'
import { Route as ApiPublicHooksProcessReceiptJobsRouteImport } from './routes/api/public/hooks/process-receipt-jobs'
import { Route as ApiPublicCronResearcherDigestRouteImport } from './routes/api/public/cron/researcher-digest'
import { Route as ParticipantDepartmentClassIdAssignmentsAssignmentIdRouteImport } from './routes/participant.department.$classId.assignments.$assignmentId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantWorkspacesRoute = ParticipantWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantFingerprintRoute = ParticipantFingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantExtensionRoute = ParticipantExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantDepartmentRoute = ParticipantDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => ParticipantRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantThreadsIndexRoute = ParticipantThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantReceiptsIndexRoute =
  ParticipantReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => ParticipantRoute,
  } as any)
const ParticipantWorkspacesWorkspaceIdRoute =
  ParticipantWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ParticipantWorkspacesRoute,
  } as any)
const ParticipantThreadsNewRoute = ParticipantThreadsNewRouteImport.update({
  id: '/threads/new',
  path: '/threads/new',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantThreadsThreadIdRoute =
  ParticipantThreadsThreadIdRouteImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => ParticipantRoute,
  } as any)
const ParticipantReceiptsReceiptIdRoute =
  ParticipantReceiptsReceiptIdRouteImport.update({
    id: '/receipts/$receiptId',
    path: '/receipts/$receiptId',
    getParentRoute: () => ParticipantRoute,
  } as any)
const ParticipantDepartmentClassIdRoute =
  ParticipantDepartmentClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => ParticipantDepartmentRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTeamOutreachRoute = ApiPublicTeamOutreachRouteImport.update({
  id: '/api/public/team-outreach',
  path: '/api/public/team-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionStatusRoute =
  ApiPublicExtensionStatusRouteImport.update({
    id: '/api/public/extension-status',
    path: '/api/public/extension-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCaptureConversationRoute =
  ApiPublicCaptureConversationRouteImport.update({
    id: '/api/public/capture-conversation',
    path: '/api/public/capture-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParticipantDepartmentClassIdThreadsRoute =
  ParticipantDepartmentClassIdThreadsRouteImport.update({
    id: '/threads',
    path: '/threads',
    getParentRoute: () => ParticipantDepartmentClassIdRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessThreadJobsRoute =
  ApiPublicHooksProcessThreadJobsRouteImport.update({
    id: '/api/public/hooks/process-thread-jobs',
    path: '/api/public/hooks/process-thread-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessReceiptJobsRoute =
  ApiPublicHooksProcessReceiptJobsRouteImport.update({
    id: '/api/public/hooks/process-receipt-jobs',
    path: '/api/public/hooks/process-receipt-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronResearcherDigestRoute =
  ApiPublicCronResearcherDigestRouteImport.update({
    id: '/api/public/cron/researcher-digest',
    path: '/api/public/cron/researcher-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute =
  ParticipantDepartmentClassIdAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => ParticipantDepartmentClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/participant': typeof ParticipantRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/participant/department': typeof ParticipantDepartmentRouteWithChildren
  '/participant/extension': typeof ParticipantExtensionRoute
  '/participant/fingerprint': typeof ParticipantFingerprintRoute
  '/participant/workspaces': typeof ParticipantWorkspacesRouteWithChildren
  '/participant/': typeof ParticipantIndexRoute
  '/api/public/capture-conversation': typeof ApiPublicCaptureConversationRoute
  '/api/public/extension-status': typeof ApiPublicExtensionStatusRoute
  '/api/public/team-outreach': typeof ApiPublicTeamOutreachRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/participant/department/$classId': typeof ParticipantDepartmentClassIdRouteWithChildren
  '/participant/receipts/$receiptId': typeof ParticipantReceiptsReceiptIdRoute
  '/participant/threads/$threadId': typeof ParticipantThreadsThreadIdRoute
  '/participant/threads/new': typeof ParticipantThreadsNewRoute
  '/participant/workspaces/$workspaceId': typeof ParticipantWorkspacesWorkspaceIdRoute
  '/participant/receipts/': typeof ParticipantReceiptsIndexRoute
  '/participant/threads/': typeof ParticipantThreadsIndexRoute
  '/api/public/cron/researcher-digest': typeof ApiPublicCronResearcherDigestRoute
  '/api/public/hooks/process-receipt-jobs': typeof ApiPublicHooksProcessReceiptJobsRoute
  '/api/public/hooks/process-thread-jobs': typeof ApiPublicHooksProcessThreadJobsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/participant/department/$classId/threads': typeof ParticipantDepartmentClassIdThreadsRoute
  '/participant/department/$classId/assignments/$assignmentId': typeof ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/participant/department': typeof ParticipantDepartmentRouteWithChildren
  '/participant/extension': typeof ParticipantExtensionRoute
  '/participant/fingerprint': typeof ParticipantFingerprintRoute
  '/participant/workspaces': typeof ParticipantWorkspacesRouteWithChildren
  '/participant': typeof ParticipantIndexRoute
  '/api/public/capture-conversation': typeof ApiPublicCaptureConversationRoute
  '/api/public/extension-status': typeof ApiPublicExtensionStatusRoute
  '/api/public/team-outreach': typeof ApiPublicTeamOutreachRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/participant/department/$classId': typeof ParticipantDepartmentClassIdRouteWithChildren
  '/participant/receipts/$receiptId': typeof ParticipantReceiptsReceiptIdRoute
  '/participant/threads/$threadId': typeof ParticipantThreadsThreadIdRoute
  '/participant/threads/new': typeof ParticipantThreadsNewRoute
  '/participant/workspaces/$workspaceId': typeof ParticipantWorkspacesWorkspaceIdRoute
  '/participant/receipts': typeof ParticipantReceiptsIndexRoute
  '/participant/threads': typeof ParticipantThreadsIndexRoute
  '/api/public/cron/researcher-digest': typeof ApiPublicCronResearcherDigestRoute
  '/api/public/hooks/process-receipt-jobs': typeof ApiPublicHooksProcessReceiptJobsRoute
  '/api/public/hooks/process-thread-jobs': typeof ApiPublicHooksProcessThreadJobsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/participant/department/$classId/threads': typeof ParticipantDepartmentClassIdThreadsRoute
  '/participant/department/$classId/assignments/$assignmentId': typeof ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/participant': typeof ParticipantRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/participant/department': typeof ParticipantDepartmentRouteWithChildren
  '/participant/extension': typeof ParticipantExtensionRoute
  '/participant/fingerprint': typeof ParticipantFingerprintRoute
  '/participant/workspaces': typeof ParticipantWorkspacesRouteWithChildren
  '/participant/': typeof ParticipantIndexRoute
  '/api/public/capture-conversation': typeof ApiPublicCaptureConversationRoute
  '/api/public/extension-status': typeof ApiPublicExtensionStatusRoute
  '/api/public/team-outreach': typeof ApiPublicTeamOutreachRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/participant/department/$classId': typeof ParticipantDepartmentClassIdRouteWithChildren
  '/participant/receipts/$receiptId': typeof ParticipantReceiptsReceiptIdRoute
  '/participant/threads/$threadId': typeof ParticipantThreadsThreadIdRoute
  '/participant/threads/new': typeof ParticipantThreadsNewRoute
  '/participant/workspaces/$workspaceId': typeof ParticipantWorkspacesWorkspaceIdRoute
  '/participant/receipts/': typeof ParticipantReceiptsIndexRoute
  '/participant/threads/': typeof ParticipantThreadsIndexRoute
  '/api/public/cron/researcher-digest': typeof ApiPublicCronResearcherDigestRoute
  '/api/public/hooks/process-receipt-jobs': typeof ApiPublicHooksProcessReceiptJobsRoute
  '/api/public/hooks/process-thread-jobs': typeof ApiPublicHooksProcessThreadJobsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/participant/department/$classId/threads': typeof ParticipantDepartmentClassIdThreadsRoute
  '/participant/department/$classId/assignments/$assignmentId': typeof ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/participant'
    | '/reset-password'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/participant/department'
    | '/participant/extension'
    | '/participant/fingerprint'
    | '/participant/workspaces'
    | '/participant/'
    | '/api/public/capture-conversation'
    | '/api/public/extension-status'
    | '/api/public/team-outreach'
    | '/lovable/email/suppression'
    | '/participant/department/$classId'
    | '/participant/receipts/$receiptId'
    | '/participant/threads/$threadId'
    | '/participant/threads/new'
    | '/participant/workspaces/$workspaceId'
    | '/participant/receipts/'
    | '/participant/threads/'
    | '/api/public/cron/researcher-digest'
    | '/api/public/hooks/process-receipt-jobs'
    | '/api/public/hooks/process-thread-jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/participant/department/$classId/threads'
    | '/participant/department/$classId/assignments/$assignmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/participant/department'
    | '/participant/extension'
    | '/participant/fingerprint'
    | '/participant/workspaces'
    | '/participant'
    | '/api/public/capture-conversation'
    | '/api/public/extension-status'
    | '/api/public/team-outreach'
    | '/lovable/email/suppression'
    | '/participant/department/$classId'
    | '/participant/receipts/$receiptId'
    | '/participant/threads/$threadId'
    | '/participant/threads/new'
    | '/participant/workspaces/$workspaceId'
    | '/participant/receipts'
    | '/participant/threads'
    | '/api/public/cron/researcher-digest'
    | '/api/public/hooks/process-receipt-jobs'
    | '/api/public/hooks/process-thread-jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/participant/department/$classId/threads'
    | '/participant/department/$classId/assignments/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/participant'
    | '/reset-password'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/participant/department'
    | '/participant/extension'
    | '/participant/fingerprint'
    | '/participant/workspaces'
    | '/participant/'
    | '/api/public/capture-conversation'
    | '/api/public/extension-status'
    | '/api/public/team-outreach'
    | '/lovable/email/suppression'
    | '/participant/department/$classId'
    | '/participant/receipts/$receiptId'
    | '/participant/threads/$threadId'
    | '/participant/threads/new'
    | '/participant/workspaces/$workspaceId'
    | '/participant/receipts/'
    | '/participant/threads/'
    | '/api/public/cron/researcher-digest'
    | '/api/public/hooks/process-receipt-jobs'
    | '/api/public/hooks/process-thread-jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/participant/department/$classId/threads'
    | '/participant/department/$classId/assignments/$assignmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ParticipantRoute: typeof ParticipantRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicCaptureConversationRoute: typeof ApiPublicCaptureConversationRoute
  ApiPublicExtensionStatusRoute: typeof ApiPublicExtensionStatusRoute
  ApiPublicTeamOutreachRoute: typeof ApiPublicTeamOutreachRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronResearcherDigestRoute: typeof ApiPublicCronResearcherDigestRoute
  ApiPublicHooksProcessReceiptJobsRoute: typeof ApiPublicHooksProcessReceiptJobsRoute
  ApiPublicHooksProcessThreadJobsRoute: typeof ApiPublicHooksProcessThreadJobsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/': {
      id: '/participant/'
      path: '/'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/workspaces': {
      id: '/participant/workspaces'
      path: '/workspaces'
      fullPath: '/participant/workspaces'
      preLoaderRoute: typeof ParticipantWorkspacesRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/fingerprint': {
      id: '/participant/fingerprint'
      path: '/fingerprint'
      fullPath: '/participant/fingerprint'
      preLoaderRoute: typeof ParticipantFingerprintRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/extension': {
      id: '/participant/extension'
      path: '/extension'
      fullPath: '/participant/extension'
      preLoaderRoute: typeof ParticipantExtensionRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/department': {
      id: '/participant/department'
      path: '/department'
      fullPath: '/participant/department'
      preLoaderRoute: typeof ParticipantDepartmentRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/threads/': {
      id: '/participant/threads/'
      path: '/threads'
      fullPath: '/participant/threads/'
      preLoaderRoute: typeof ParticipantThreadsIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/receipts/': {
      id: '/participant/receipts/'
      path: '/receipts'
      fullPath: '/participant/receipts/'
      preLoaderRoute: typeof ParticipantReceiptsIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/workspaces/$workspaceId': {
      id: '/participant/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/participant/workspaces/$workspaceId'
      preLoaderRoute: typeof ParticipantWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ParticipantWorkspacesRoute
    }
    '/participant/threads/new': {
      id: '/participant/threads/new'
      path: '/threads/new'
      fullPath: '/participant/threads/new'
      preLoaderRoute: typeof ParticipantThreadsNewRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/threads/$threadId': {
      id: '/participant/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/participant/threads/$threadId'
      preLoaderRoute: typeof ParticipantThreadsThreadIdRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/receipts/$receiptId': {
      id: '/participant/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/participant/receipts/$receiptId'
      preLoaderRoute: typeof ParticipantReceiptsReceiptIdRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/department/$classId': {
      id: '/participant/department/$classId'
      path: '/$classId'
      fullPath: '/participant/department/$classId'
      preLoaderRoute: typeof ParticipantDepartmentClassIdRouteImport
      parentRoute: typeof ParticipantDepartmentRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/team-outreach': {
      id: '/api/public/team-outreach'
      path: '/api/public/team-outreach'
      fullPath: '/api/public/team-outreach'
      preLoaderRoute: typeof ApiPublicTeamOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension-status': {
      id: '/api/public/extension-status'
      path: '/api/public/extension-status'
      fullPath: '/api/public/extension-status'
      preLoaderRoute: typeof ApiPublicExtensionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capture-conversation': {
      id: '/api/public/capture-conversation'
      path: '/api/public/capture-conversation'
      fullPath: '/api/public/capture-conversation'
      preLoaderRoute: typeof ApiPublicCaptureConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/department/$classId/threads': {
      id: '/participant/department/$classId/threads'
      path: '/threads'
      fullPath: '/participant/department/$classId/threads'
      preLoaderRoute: typeof ParticipantDepartmentClassIdThreadsRouteImport
      parentRoute: typeof ParticipantDepartmentClassIdRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-thread-jobs': {
      id: '/api/public/hooks/process-thread-jobs'
      path: '/api/public/hooks/process-thread-jobs'
      fullPath: '/api/public/hooks/process-thread-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessThreadJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-receipt-jobs': {
      id: '/api/public/hooks/process-receipt-jobs'
      path: '/api/public/hooks/process-receipt-jobs'
      fullPath: '/api/public/hooks/process-receipt-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessReceiptJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/researcher-digest': {
      id: '/api/public/cron/researcher-digest'
      path: '/api/public/cron/researcher-digest'
      fullPath: '/api/public/cron/researcher-digest'
      preLoaderRoute: typeof ApiPublicCronResearcherDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/department/$classId/assignments/$assignmentId': {
      id: '/participant/department/$classId/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/participant/department/$classId/assignments/$assignmentId'
      preLoaderRoute: typeof ParticipantDepartmentClassIdAssignmentsAssignmentIdRouteImport
      parentRoute: typeof ParticipantDepartmentClassIdRoute
    }
  }
}

interface ParticipantDepartmentClassIdRouteChildren {
  ParticipantDepartmentClassIdThreadsRoute: typeof ParticipantDepartmentClassIdThreadsRoute
  ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute: typeof ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute
}

const ParticipantDepartmentClassIdRouteChildren: ParticipantDepartmentClassIdRouteChildren =
  {
    ParticipantDepartmentClassIdThreadsRoute:
      ParticipantDepartmentClassIdThreadsRoute,
    ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute:
      ParticipantDepartmentClassIdAssignmentsAssignmentIdRoute,
  }

const ParticipantDepartmentClassIdRouteWithChildren =
  ParticipantDepartmentClassIdRoute._addFileChildren(
    ParticipantDepartmentClassIdRouteChildren,
  )

interface ParticipantDepartmentRouteChildren {
  ParticipantDepartmentClassIdRoute: typeof ParticipantDepartmentClassIdRouteWithChildren
}

const ParticipantDepartmentRouteChildren: ParticipantDepartmentRouteChildren = {
  ParticipantDepartmentClassIdRoute:
    ParticipantDepartmentClassIdRouteWithChildren,
}

const ParticipantDepartmentRouteWithChildren =
  ParticipantDepartmentRoute._addFileChildren(
    ParticipantDepartmentRouteChildren,
  )

interface ParticipantWorkspacesRouteChildren {
  ParticipantWorkspacesWorkspaceIdRoute: typeof ParticipantWorkspacesWorkspaceIdRoute
}

const ParticipantWorkspacesRouteChildren: ParticipantWorkspacesRouteChildren = {
  ParticipantWorkspacesWorkspaceIdRoute: ParticipantWorkspacesWorkspaceIdRoute,
}

const ParticipantWorkspacesRouteWithChildren =
  ParticipantWorkspacesRoute._addFileChildren(
    ParticipantWorkspacesRouteChildren,
  )

interface ParticipantRouteChildren {
  ParticipantDepartmentRoute: typeof ParticipantDepartmentRouteWithChildren
  ParticipantExtensionRoute: typeof ParticipantExtensionRoute
  ParticipantFingerprintRoute: typeof ParticipantFingerprintRoute
  ParticipantWorkspacesRoute: typeof ParticipantWorkspacesRouteWithChildren
  ParticipantIndexRoute: typeof ParticipantIndexRoute
  ParticipantReceiptsReceiptIdRoute: typeof ParticipantReceiptsReceiptIdRoute
  ParticipantThreadsThreadIdRoute: typeof ParticipantThreadsThreadIdRoute
  ParticipantThreadsNewRoute: typeof ParticipantThreadsNewRoute
  ParticipantReceiptsIndexRoute: typeof ParticipantReceiptsIndexRoute
  ParticipantThreadsIndexRoute: typeof ParticipantThreadsIndexRoute
}

const ParticipantRouteChildren: ParticipantRouteChildren = {
  ParticipantDepartmentRoute: ParticipantDepartmentRouteWithChildren,
  ParticipantExtensionRoute: ParticipantExtensionRoute,
  ParticipantFingerprintRoute: ParticipantFingerprintRoute,
  ParticipantWorkspacesRoute: ParticipantWorkspacesRouteWithChildren,
  ParticipantIndexRoute: ParticipantIndexRoute,
  ParticipantReceiptsReceiptIdRoute: ParticipantReceiptsReceiptIdRoute,
  ParticipantThreadsThreadIdRoute: ParticipantThreadsThreadIdRoute,
  ParticipantThreadsNewRoute: ParticipantThreadsNewRoute,
  ParticipantReceiptsIndexRoute: ParticipantReceiptsIndexRoute,
  ParticipantThreadsIndexRoute: ParticipantThreadsIndexRoute,
}

const ParticipantRouteWithChildren = ParticipantRoute._addFileChildren(
  ParticipantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ParticipantRoute: ParticipantRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicCaptureConversationRoute: ApiPublicCaptureConversationRoute,
  ApiPublicExtensionStatusRoute: ApiPublicExtensionStatusRoute,
  ApiPublicTeamOutreachRoute: ApiPublicTeamOutreachRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronResearcherDigestRoute: ApiPublicCronResearcherDigestRoute,
  ApiPublicHooksProcessReceiptJobsRoute: ApiPublicHooksProcessReceiptJobsRoute,
  ApiPublicHooksProcessThreadJobsRoute: ApiPublicHooksProcessThreadJobsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
