/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearcherRouteImport } from './routes/researcher'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearcherIndexRouteImport } from './routes/researcher.index'
import { Route as ParticipantIndexRouteImport } from './routes/participant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ParticipantWorkspacesRouteImport } from './routes/participant.workspaces'
import { Route as ParticipantWorkflowsRouteImport } from './routes/participant.workflows'
import { Route as ParticipantHowItWorksRouteImport } from './routes/participant.how-it-works'
import { Route as ParticipantFingerprintRouteImport } from './routes/participant.fingerprint'
import { Route as ParticipantExtensionRouteImport } from './routes/participant.extension'
import { Route as ParticipantDemoRouteImport } from './routes/participant.demo'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminTeamOutreachRouteImport } from './routes/admin.team-outreach'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminReceiptRunsRouteImport } from './routes/admin.receipt-runs'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as ParticipantThreadsIndexRouteImport } from './routes/participant.threads.index'
import { Route as ParticipantReceiptsIndexRouteImport } from './routes/participant.receipts.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as ShareProofReceiptIdRouteImport } from './routes/share.proof.$receiptId'
import { Route as ResearcherSessionsSessionIdRouteImport } from './routes/researcher.sessions.$sessionId'
import { Route as ResearcherConversationsConvIdRouteImport } from './routes/researcher.conversations.$convId'
import { Route as ParticipantWorkspacesWorkspaceIdRouteImport } from './routes/participant.workspaces.$workspaceId'
import { Route as ParticipantThreadsNewRouteImport } from './routes/participant.threads.new'
import { Route as ParticipantThreadsThreadIdRouteImport } from './routes/participant.threads.$threadId'
import { Route as ParticipantReceiptsReceiptIdRouteImport } from './routes/participant.receipts.$receiptId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTeamOutreachRouteImport } from './routes/api/public/team-outreach'
import { Route as ApiPublicExtensionStatusRouteImport } from './routes/api/public/extension-status'
import { Route as ApiPublicCaptureConversationRouteImport } from './routes/api/public/capture-conversation'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminThreadsThreadIdRouteImport } from './routes/admin.threads.$threadId'
import { Route as AdminSessionsSessionIdRouteImport } from './routes/admin.sessions.$sessionId'
import { Route as AdminReceiptsReceiptIdRouteImport } from './routes/admin.receipts.$receiptId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksProcessThreadJobsRouteImport } from './routes/api/public/hooks/process-thread-jobs'
import { Route as ApiPublicHooksProcessReceiptJobsRouteImport } from './routes/api/public/hooks/process-receipt-jobs'
import { Route as ApiPublicCronResearcherDigestRouteImport } from './routes/api/public/cron/researcher-digest'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherRoute = ResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherIndexRoute = ResearcherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearcherRoute,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipantRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ParticipantWorkspacesRoute = ParticipantWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantWorkflowsRoute = ParticipantWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantHowItWorksRoute = ParticipantHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantFingerprintRoute = ParticipantFingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantExtensionRoute = ParticipantExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantDemoRoute = ParticipantDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => ParticipantRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamOutreachRoute = AdminTeamOutreachRouteImport.update({
  id: '/team-outreach',
  path: '/team-outreach',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceiptRunsRoute = AdminReceiptRunsRouteImport.update({
  id: '/receipt-runs',
  path: '/receipt-runs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const ParticipantThreadsIndexRoute = ParticipantThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantReceiptsIndexRoute =
  ParticipantReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => ParticipantRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const ShareProofReceiptIdRoute = ShareProofReceiptIdRouteImport.update({
  id: '/share/proof/$receiptId',
  path: '/share/proof/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearcherSessionsSessionIdRoute =
  ResearcherSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => ResearcherRoute,
  } as any)
const ResearcherConversationsConvIdRoute =
  ResearcherConversationsConvIdRouteImport.update({
    id: '/conversations/$convId',
    path: '/conversations/$convId',
    getParentRoute: () => ResearcherRoute,
  } as any)
const ParticipantWorkspacesWorkspaceIdRoute =
  ParticipantWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ParticipantWorkspacesRoute,
  } as any)
const ParticipantThreadsNewRoute = ParticipantThreadsNewRouteImport.update({
  id: '/threads/new',
  path: '/threads/new',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantThreadsThreadIdRoute =
  ParticipantThreadsThreadIdRouteImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => ParticipantRoute,
  } as any)
const ParticipantReceiptsReceiptIdRoute =
  ParticipantReceiptsReceiptIdRouteImport.update({
    id: '/receipts/$receiptId',
    path: '/receipts/$receiptId',
    getParentRoute: () => ParticipantRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTeamOutreachRoute = ApiPublicTeamOutreachRouteImport.update({
  id: '/api/public/team-outreach',
  path: '/api/public/team-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionStatusRoute =
  ApiPublicExtensionStatusRouteImport.update({
    id: '/api/public/extension-status',
    path: '/api/public/extension-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCaptureConversationRoute =
  ApiPublicCaptureConversationRouteImport.update({
    id: '/api/public/capture-conversation',
    path: '/api/public/capture-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThreadsThreadIdRoute = AdminThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsSessionIdRoute = AdminSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AdminSessionsRoute,
} as any)
const AdminReceiptsReceiptIdRoute = AdminReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessThreadJobsRoute =
  ApiPublicHooksProcessThreadJobsRouteImport.update({
    id: '/api/public/hooks/process-thread-jobs',
    path: '/api/public/hooks/process-thread-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessReceiptJobsRoute =
  ApiPublicHooksProcessReceiptJobsRouteImport.update({
    id: '/api/public/hooks/process-receipt-jobs',
    path: '/api/public/hooks/process-receipt-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronResearcherDigestRoute =
  ApiPublicCronResearcherDigestRouteImport.update({
    id: '/api/public/cron/researcher-digest',
    path: '/api/public/cron/researcher-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/participant': typeof ParticipantRouteWithChildren
  '/researcher': typeof ResearcherRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/receipt-runs': typeof AdminReceiptRunsRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/team-outreach': typeof AdminTeamOutreachRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/participant/demo': typeof ParticipantDemoRoute
  '/participant/extension': typeof ParticipantExtensionRoute
  '/participant/fingerprint': typeof ParticipantFingerprintRoute
  '/participant/how-it-works': typeof ParticipantHowItWorksRoute
  '/participant/workflows': typeof ParticipantWorkflowsRoute
  '/participant/workspaces': typeof ParticipantWorkspacesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/researcher/': typeof ResearcherIndexRoute
  '/admin/receipts/$receiptId': typeof AdminReceiptsReceiptIdRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/threads/$threadId': typeof AdminThreadsThreadIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/capture-conversation': typeof ApiPublicCaptureConversationRoute
  '/api/public/extension-status': typeof ApiPublicExtensionStatusRoute
  '/api/public/team-outreach': typeof ApiPublicTeamOutreachRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/participant/receipts/$receiptId': typeof ParticipantReceiptsReceiptIdRoute
  '/participant/threads/$threadId': typeof ParticipantThreadsThreadIdRoute
  '/participant/threads/new': typeof ParticipantThreadsNewRoute
  '/participant/workspaces/$workspaceId': typeof ParticipantWorkspacesWorkspaceIdRoute
  '/researcher/conversations/$convId': typeof ResearcherConversationsConvIdRoute
  '/researcher/sessions/$sessionId': typeof ResearcherSessionsSessionIdRoute
  '/share/proof/$receiptId': typeof ShareProofReceiptIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/participant/receipts/': typeof ParticipantReceiptsIndexRoute
  '/participant/threads/': typeof ParticipantThreadsIndexRoute
  '/api/public/cron/researcher-digest': typeof ApiPublicCronResearcherDigestRoute
  '/api/public/hooks/process-receipt-jobs': typeof ApiPublicHooksProcessReceiptJobsRoute
  '/api/public/hooks/process-thread-jobs': typeof ApiPublicHooksProcessThreadJobsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/receipt-runs': typeof AdminReceiptRunsRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/team-outreach': typeof AdminTeamOutreachRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/participant/demo': typeof ParticipantDemoRoute
  '/participant/extension': typeof ParticipantExtensionRoute
  '/participant/fingerprint': typeof ParticipantFingerprintRoute
  '/participant/how-it-works': typeof ParticipantHowItWorksRoute
  '/participant/workflows': typeof ParticipantWorkflowsRoute
  '/participant/workspaces': typeof ParticipantWorkspacesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/researcher': typeof ResearcherIndexRoute
  '/admin/receipts/$receiptId': typeof AdminReceiptsReceiptIdRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/threads/$threadId': typeof AdminThreadsThreadIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/capture-conversation': typeof ApiPublicCaptureConversationRoute
  '/api/public/extension-status': typeof ApiPublicExtensionStatusRoute
  '/api/public/team-outreach': typeof ApiPublicTeamOutreachRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/participant/receipts/$receiptId': typeof ParticipantReceiptsReceiptIdRoute
  '/participant/threads/$threadId': typeof ParticipantThreadsThreadIdRoute
  '/participant/threads/new': typeof ParticipantThreadsNewRoute
  '/participant/workspaces/$workspaceId': typeof ParticipantWorkspacesWorkspaceIdRoute
  '/researcher/conversations/$convId': typeof ResearcherConversationsConvIdRoute
  '/researcher/sessions/$sessionId': typeof ResearcherSessionsSessionIdRoute
  '/share/proof/$receiptId': typeof ShareProofReceiptIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/participant/receipts': typeof ParticipantReceiptsIndexRoute
  '/participant/threads': typeof ParticipantThreadsIndexRoute
  '/api/public/cron/researcher-digest': typeof ApiPublicCronResearcherDigestRoute
  '/api/public/hooks/process-receipt-jobs': typeof ApiPublicHooksProcessReceiptJobsRoute
  '/api/public/hooks/process-thread-jobs': typeof ApiPublicHooksProcessThreadJobsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/participant': typeof ParticipantRouteWithChildren
  '/researcher': typeof ResearcherRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/receipt-runs': typeof AdminReceiptRunsRoute
  '/admin/sessions': typeof AdminSessionsRouteWithChildren
  '/admin/team-outreach': typeof AdminTeamOutreachRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/participant/demo': typeof ParticipantDemoRoute
  '/participant/extension': typeof ParticipantExtensionRoute
  '/participant/fingerprint': typeof ParticipantFingerprintRoute
  '/participant/how-it-works': typeof ParticipantHowItWorksRoute
  '/participant/workflows': typeof ParticipantWorkflowsRoute
  '/participant/workspaces': typeof ParticipantWorkspacesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/researcher/': typeof ResearcherIndexRoute
  '/admin/receipts/$receiptId': typeof AdminReceiptsReceiptIdRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
  '/admin/threads/$threadId': typeof AdminThreadsThreadIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/capture-conversation': typeof ApiPublicCaptureConversationRoute
  '/api/public/extension-status': typeof ApiPublicExtensionStatusRoute
  '/api/public/team-outreach': typeof ApiPublicTeamOutreachRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/participant/receipts/$receiptId': typeof ParticipantReceiptsReceiptIdRoute
  '/participant/threads/$threadId': typeof ParticipantThreadsThreadIdRoute
  '/participant/threads/new': typeof ParticipantThreadsNewRoute
  '/participant/workspaces/$workspaceId': typeof ParticipantWorkspacesWorkspaceIdRoute
  '/researcher/conversations/$convId': typeof ResearcherConversationsConvIdRoute
  '/researcher/sessions/$sessionId': typeof ResearcherSessionsSessionIdRoute
  '/share/proof/$receiptId': typeof ShareProofReceiptIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/participant/receipts/': typeof ParticipantReceiptsIndexRoute
  '/participant/threads/': typeof ParticipantThreadsIndexRoute
  '/api/public/cron/researcher-digest': typeof ApiPublicCronResearcherDigestRoute
  '/api/public/hooks/process-receipt-jobs': typeof ApiPublicHooksProcessReceiptJobsRoute
  '/api/public/hooks/process-thread-jobs': typeof ApiPublicHooksProcessThreadJobsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/participant'
    | '/researcher'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin/conversations'
    | '/admin/emails'
    | '/admin/receipt-runs'
    | '/admin/sessions'
    | '/admin/team-outreach'
    | '/email/unsubscribe'
    | '/participant/demo'
    | '/participant/extension'
    | '/participant/fingerprint'
    | '/participant/how-it-works'
    | '/participant/workflows'
    | '/participant/workspaces'
    | '/admin/'
    | '/participant/'
    | '/researcher/'
    | '/admin/receipts/$receiptId'
    | '/admin/sessions/$sessionId'
    | '/admin/threads/$threadId'
    | '/admin/users/$userId'
    | '/api/public/capture-conversation'
    | '/api/public/extension-status'
    | '/api/public/team-outreach'
    | '/lovable/email/suppression'
    | '/participant/receipts/$receiptId'
    | '/participant/threads/$threadId'
    | '/participant/threads/new'
    | '/participant/workspaces/$workspaceId'
    | '/researcher/conversations/$convId'
    | '/researcher/sessions/$sessionId'
    | '/share/proof/$receiptId'
    | '/admin/users/'
    | '/participant/receipts/'
    | '/participant/threads/'
    | '/api/public/cron/researcher-digest'
    | '/api/public/hooks/process-receipt-jobs'
    | '/api/public/hooks/process-thread-jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin/conversations'
    | '/admin/emails'
    | '/admin/receipt-runs'
    | '/admin/sessions'
    | '/admin/team-outreach'
    | '/email/unsubscribe'
    | '/participant/demo'
    | '/participant/extension'
    | '/participant/fingerprint'
    | '/participant/how-it-works'
    | '/participant/workflows'
    | '/participant/workspaces'
    | '/admin'
    | '/participant'
    | '/researcher'
    | '/admin/receipts/$receiptId'
    | '/admin/sessions/$sessionId'
    | '/admin/threads/$threadId'
    | '/admin/users/$userId'
    | '/api/public/capture-conversation'
    | '/api/public/extension-status'
    | '/api/public/team-outreach'
    | '/lovable/email/suppression'
    | '/participant/receipts/$receiptId'
    | '/participant/threads/$threadId'
    | '/participant/threads/new'
    | '/participant/workspaces/$workspaceId'
    | '/researcher/conversations/$convId'
    | '/researcher/sessions/$sessionId'
    | '/share/proof/$receiptId'
    | '/admin/users'
    | '/participant/receipts'
    | '/participant/threads'
    | '/api/public/cron/researcher-digest'
    | '/api/public/hooks/process-receipt-jobs'
    | '/api/public/hooks/process-thread-jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/participant'
    | '/researcher'
    | '/reset-password'
    | '/unsubscribe'
    | '/admin/conversations'
    | '/admin/emails'
    | '/admin/receipt-runs'
    | '/admin/sessions'
    | '/admin/team-outreach'
    | '/email/unsubscribe'
    | '/participant/demo'
    | '/participant/extension'
    | '/participant/fingerprint'
    | '/participant/how-it-works'
    | '/participant/workflows'
    | '/participant/workspaces'
    | '/admin/'
    | '/participant/'
    | '/researcher/'
    | '/admin/receipts/$receiptId'
    | '/admin/sessions/$sessionId'
    | '/admin/threads/$threadId'
    | '/admin/users/$userId'
    | '/api/public/capture-conversation'
    | '/api/public/extension-status'
    | '/api/public/team-outreach'
    | '/lovable/email/suppression'
    | '/participant/receipts/$receiptId'
    | '/participant/threads/$threadId'
    | '/participant/threads/new'
    | '/participant/workspaces/$workspaceId'
    | '/researcher/conversations/$convId'
    | '/researcher/sessions/$sessionId'
    | '/share/proof/$receiptId'
    | '/admin/users/'
    | '/participant/receipts/'
    | '/participant/threads/'
    | '/api/public/cron/researcher-digest'
    | '/api/public/hooks/process-receipt-jobs'
    | '/api/public/hooks/process-thread-jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ParticipantRoute: typeof ParticipantRouteWithChildren
  ResearcherRoute: typeof ResearcherRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicCaptureConversationRoute: typeof ApiPublicCaptureConversationRoute
  ApiPublicExtensionStatusRoute: typeof ApiPublicExtensionStatusRoute
  ApiPublicTeamOutreachRoute: typeof ApiPublicTeamOutreachRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ShareProofReceiptIdRoute: typeof ShareProofReceiptIdRoute
  ApiPublicCronResearcherDigestRoute: typeof ApiPublicCronResearcherDigestRoute
  ApiPublicHooksProcessReceiptJobsRoute: typeof ApiPublicHooksProcessReceiptJobsRoute
  ApiPublicHooksProcessThreadJobsRoute: typeof ApiPublicHooksProcessThreadJobsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher': {
      id: '/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof ResearcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher/': {
      id: '/researcher/'
      path: '/'
      fullPath: '/researcher/'
      preLoaderRoute: typeof ResearcherIndexRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/participant/': {
      id: '/participant/'
      path: '/'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/participant/workspaces': {
      id: '/participant/workspaces'
      path: '/workspaces'
      fullPath: '/participant/workspaces'
      preLoaderRoute: typeof ParticipantWorkspacesRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/workflows': {
      id: '/participant/workflows'
      path: '/workflows'
      fullPath: '/participant/workflows'
      preLoaderRoute: typeof ParticipantWorkflowsRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/how-it-works': {
      id: '/participant/how-it-works'
      path: '/how-it-works'
      fullPath: '/participant/how-it-works'
      preLoaderRoute: typeof ParticipantHowItWorksRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/fingerprint': {
      id: '/participant/fingerprint'
      path: '/fingerprint'
      fullPath: '/participant/fingerprint'
      preLoaderRoute: typeof ParticipantFingerprintRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/extension': {
      id: '/participant/extension'
      path: '/extension'
      fullPath: '/participant/extension'
      preLoaderRoute: typeof ParticipantExtensionRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/demo': {
      id: '/participant/demo'
      path: '/demo'
      fullPath: '/participant/demo'
      preLoaderRoute: typeof ParticipantDemoRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team-outreach': {
      id: '/admin/team-outreach'
      path: '/team-outreach'
      fullPath: '/admin/team-outreach'
      preLoaderRoute: typeof AdminTeamOutreachRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receipt-runs': {
      id: '/admin/receipt-runs'
      path: '/receipt-runs'
      fullPath: '/admin/receipt-runs'
      preLoaderRoute: typeof AdminReceiptRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/participant/threads/': {
      id: '/participant/threads/'
      path: '/threads'
      fullPath: '/participant/threads/'
      preLoaderRoute: typeof ParticipantThreadsIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/receipts/': {
      id: '/participant/receipts/'
      path: '/receipts'
      fullPath: '/participant/receipts/'
      preLoaderRoute: typeof ParticipantReceiptsIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/share/proof/$receiptId': {
      id: '/share/proof/$receiptId'
      path: '/share/proof/$receiptId'
      fullPath: '/share/proof/$receiptId'
      preLoaderRoute: typeof ShareProofReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researcher/sessions/$sessionId': {
      id: '/researcher/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/researcher/sessions/$sessionId'
      preLoaderRoute: typeof ResearcherSessionsSessionIdRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/researcher/conversations/$convId': {
      id: '/researcher/conversations/$convId'
      path: '/conversations/$convId'
      fullPath: '/researcher/conversations/$convId'
      preLoaderRoute: typeof ResearcherConversationsConvIdRouteImport
      parentRoute: typeof ResearcherRoute
    }
    '/participant/workspaces/$workspaceId': {
      id: '/participant/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/participant/workspaces/$workspaceId'
      preLoaderRoute: typeof ParticipantWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ParticipantWorkspacesRoute
    }
    '/participant/threads/new': {
      id: '/participant/threads/new'
      path: '/threads/new'
      fullPath: '/participant/threads/new'
      preLoaderRoute: typeof ParticipantThreadsNewRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/threads/$threadId': {
      id: '/participant/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/participant/threads/$threadId'
      preLoaderRoute: typeof ParticipantThreadsThreadIdRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/receipts/$receiptId': {
      id: '/participant/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/participant/receipts/$receiptId'
      preLoaderRoute: typeof ParticipantReceiptsReceiptIdRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/team-outreach': {
      id: '/api/public/team-outreach'
      path: '/api/public/team-outreach'
      fullPath: '/api/public/team-outreach'
      preLoaderRoute: typeof ApiPublicTeamOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension-status': {
      id: '/api/public/extension-status'
      path: '/api/public/extension-status'
      fullPath: '/api/public/extension-status'
      preLoaderRoute: typeof ApiPublicExtensionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capture-conversation': {
      id: '/api/public/capture-conversation'
      path: '/api/public/capture-conversation'
      fullPath: '/api/public/capture-conversation'
      preLoaderRoute: typeof ApiPublicCaptureConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/threads/$threadId': {
      id: '/admin/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/admin/threads/$threadId'
      preLoaderRoute: typeof AdminThreadsThreadIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/$sessionId': {
      id: '/admin/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/admin/sessions/$sessionId'
      preLoaderRoute: typeof AdminSessionsSessionIdRouteImport
      parentRoute: typeof AdminSessionsRoute
    }
    '/admin/receipts/$receiptId': {
      id: '/admin/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/admin/receipts/$receiptId'
      preLoaderRoute: typeof AdminReceiptsReceiptIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-thread-jobs': {
      id: '/api/public/hooks/process-thread-jobs'
      path: '/api/public/hooks/process-thread-jobs'
      fullPath: '/api/public/hooks/process-thread-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessThreadJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-receipt-jobs': {
      id: '/api/public/hooks/process-receipt-jobs'
      path: '/api/public/hooks/process-receipt-jobs'
      fullPath: '/api/public/hooks/process-receipt-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessReceiptJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/researcher-digest': {
      id: '/api/public/cron/researcher-digest'
      path: '/api/public/cron/researcher-digest'
      fullPath: '/api/public/cron/researcher-digest'
      preLoaderRoute: typeof ApiPublicCronResearcherDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSessionsRouteChildren {
  AdminSessionsSessionIdRoute: typeof AdminSessionsSessionIdRoute
}

const AdminSessionsRouteChildren: AdminSessionsRouteChildren = {
  AdminSessionsSessionIdRoute: AdminSessionsSessionIdRoute,
}

const AdminSessionsRouteWithChildren = AdminSessionsRoute._addFileChildren(
  AdminSessionsRouteChildren,
)

interface AdminRouteChildren {
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminReceiptRunsRoute: typeof AdminReceiptRunsRoute
  AdminSessionsRoute: typeof AdminSessionsRouteWithChildren
  AdminTeamOutreachRoute: typeof AdminTeamOutreachRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReceiptsReceiptIdRoute: typeof AdminReceiptsReceiptIdRoute
  AdminThreadsThreadIdRoute: typeof AdminThreadsThreadIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConversationsRoute: AdminConversationsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminReceiptRunsRoute: AdminReceiptRunsRoute,
  AdminSessionsRoute: AdminSessionsRouteWithChildren,
  AdminTeamOutreachRoute: AdminTeamOutreachRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReceiptsReceiptIdRoute: AdminReceiptsReceiptIdRoute,
  AdminThreadsThreadIdRoute: AdminThreadsThreadIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParticipantWorkspacesRouteChildren {
  ParticipantWorkspacesWorkspaceIdRoute: typeof ParticipantWorkspacesWorkspaceIdRoute
}

const ParticipantWorkspacesRouteChildren: ParticipantWorkspacesRouteChildren = {
  ParticipantWorkspacesWorkspaceIdRoute: ParticipantWorkspacesWorkspaceIdRoute,
}

const ParticipantWorkspacesRouteWithChildren =
  ParticipantWorkspacesRoute._addFileChildren(
    ParticipantWorkspacesRouteChildren,
  )

interface ParticipantRouteChildren {
  ParticipantDemoRoute: typeof ParticipantDemoRoute
  ParticipantExtensionRoute: typeof ParticipantExtensionRoute
  ParticipantFingerprintRoute: typeof ParticipantFingerprintRoute
  ParticipantHowItWorksRoute: typeof ParticipantHowItWorksRoute
  ParticipantWorkflowsRoute: typeof ParticipantWorkflowsRoute
  ParticipantWorkspacesRoute: typeof ParticipantWorkspacesRouteWithChildren
  ParticipantIndexRoute: typeof ParticipantIndexRoute
  ParticipantReceiptsReceiptIdRoute: typeof ParticipantReceiptsReceiptIdRoute
  ParticipantThreadsThreadIdRoute: typeof ParticipantThreadsThreadIdRoute
  ParticipantThreadsNewRoute: typeof ParticipantThreadsNewRoute
  ParticipantReceiptsIndexRoute: typeof ParticipantReceiptsIndexRoute
  ParticipantThreadsIndexRoute: typeof ParticipantThreadsIndexRoute
}

const ParticipantRouteChildren: ParticipantRouteChildren = {
  ParticipantDemoRoute: ParticipantDemoRoute,
  ParticipantExtensionRoute: ParticipantExtensionRoute,
  ParticipantFingerprintRoute: ParticipantFingerprintRoute,
  ParticipantHowItWorksRoute: ParticipantHowItWorksRoute,
  ParticipantWorkflowsRoute: ParticipantWorkflowsRoute,
  ParticipantWorkspacesRoute: ParticipantWorkspacesRouteWithChildren,
  ParticipantIndexRoute: ParticipantIndexRoute,
  ParticipantReceiptsReceiptIdRoute: ParticipantReceiptsReceiptIdRoute,
  ParticipantThreadsThreadIdRoute: ParticipantThreadsThreadIdRoute,
  ParticipantThreadsNewRoute: ParticipantThreadsNewRoute,
  ParticipantReceiptsIndexRoute: ParticipantReceiptsIndexRoute,
  ParticipantThreadsIndexRoute: ParticipantThreadsIndexRoute,
}

const ParticipantRouteWithChildren = ParticipantRoute._addFileChildren(
  ParticipantRouteChildren,
)

interface ResearcherRouteChildren {
  ResearcherIndexRoute: typeof ResearcherIndexRoute
  ResearcherConversationsConvIdRoute: typeof ResearcherConversationsConvIdRoute
  ResearcherSessionsSessionIdRoute: typeof ResearcherSessionsSessionIdRoute
}

const ResearcherRouteChildren: ResearcherRouteChildren = {
  ResearcherIndexRoute: ResearcherIndexRoute,
  ResearcherConversationsConvIdRoute: ResearcherConversationsConvIdRoute,
  ResearcherSessionsSessionIdRoute: ResearcherSessionsSessionIdRoute,
}

const ResearcherRouteWithChildren = ResearcherRoute._addFileChildren(
  ResearcherRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ParticipantRoute: ParticipantRouteWithChildren,
  ResearcherRoute: ResearcherRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicCaptureConversationRoute: ApiPublicCaptureConversationRoute,
  ApiPublicExtensionStatusRoute: ApiPublicExtensionStatusRoute,
  ApiPublicTeamOutreachRoute: ApiPublicTeamOutreachRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ShareProofReceiptIdRoute: ShareProofReceiptIdRoute,
  ApiPublicCronResearcherDigestRoute: ApiPublicCronResearcherDigestRoute,
  ApiPublicHooksProcessReceiptJobsRoute: ApiPublicHooksProcessReceiptJobsRoute,
  ApiPublicHooksProcessThreadJobsRoute: ApiPublicHooksProcessThreadJobsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
